version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
  - dependency-name: capybara
    versions:
    - 3.35.1
